# auth-service.yml dans le dépôt Git du Config Server
server:
  port: 8004

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://auth_htmx_user:qDdbNDIspJXGntagaEDXe4ciHTWHaESi@dpg-d0uphcbipnbc73epda20-a/auth_htmx
    username: auth_htmx_user
    password: qDdbNDIspJXGntagaEDXe4ciHTWHaESi
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 86400000
